<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="4" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="86" started-at="2017-04-20T05:28:27Z" finished-at="2017-04-20T05:28:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="86" started-at="2017-04-20T05:28:27Z" finished-at="2017-04-20T05:28:27Z">
      <class name="com.Testing.TestNgSample.TestEmployeeFunc">
        <test-method status="PASS" signature="testCalculateAppriasal()[pri:0, instance:com.Testing.TestNgSample.TestEmployeeFunc@47c62251]" name="testCalculateAppriasal" duration-ms="17" started-at="2017-04-20T10:58:27Z" finished-at="2017-04-20T10:58:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCalculateAppriasal -->
        <test-method status="PASS" signature="testCalculateYearlySalary()[pri:0, instance:com.Testing.TestNgSample.TestEmployeeFunc@47c62251]" name="testCalculateYearlySalary" duration-ms="5" started-at="2017-04-20T10:58:27Z" finished-at="2017-04-20T10:58:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCalculateYearlySalary -->
        <test-method status="PASS" signature="testInvalidAgeValue()[pri:0, instance:com.Testing.TestNgSample.TestEmployeeFunc@47c62251]" name="testInvalidAgeValue" duration-ms="13" started-at="2017-04-20T10:58:27Z" finished-at="2017-04-20T10:58:27Z">
          <exception class="com.Testing.TestNgSample.InvalidAge">
            <full-stacktrace>
              <![CDATA[com.Testing.TestNgSample.InvalidAge
	at com.Testing.TestNgSample.Employee.setAge(Employee.java:44)
	at com.Testing.TestNgSample.TestEmployeeFunc.testInvalidAgeValue(TestEmployeeFunc.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.Testing.TestNgSample.InvalidAge -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidAgeValue -->
        <test-method status="PASS" signature="testInvalidSalaryValue()[pri:0, instance:com.Testing.TestNgSample.TestEmployeeFunc@47c62251]" name="testInvalidSalaryValue" duration-ms="3" started-at="2017-04-20T10:58:27Z" finished-at="2017-04-20T10:58:27Z">
          <exception class="com.Testing.TestNgSample.InvalidSalary">
            <full-stacktrace>
              <![CDATA[com.Testing.TestNgSample.InvalidSalary
	at com.Testing.TestNgSample.Employee.setSalary(Employee.java:53)
	at com.Testing.TestNgSample.TestEmployeeFunc.testInvalidSalaryValue(TestEmployeeFunc.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.Testing.TestNgSample.InvalidSalary -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidSalaryValue -->
      </class> <!-- com.Testing.TestNgSample.TestEmployeeFunc -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
